# appear_luz_applyt_dsl.py - genera el DSL de BPC_AppearLuz_SC.ApplyT (la coreografia 'luz primero', los MISMOS numeros
# que blender-3d/scripts/anim_luz_objects.py). Uso: python appear_luz_applyt_dsl.py > applyt.dsl
def cl(x):
    return "(Math|Float|Clamp(Float) %s 0.0 1.0)" % x
def seg(v, a, b):
    return cl("(/ (- %s %s) %s)" % (v, a, round(b - a, 4))) if a else cl("(/ %s %s)" % (v, b))
def S(x):
    return "(* %s (* %s (- 3.0 (* 2.0 %s))))" % (x, x, x)
L = []
B = L.append
B("(fn ApplyT (Tin)")
B(" (bind t %s)" % cl("Tin"))
B(" (bind tb (select (Variables|Default|GetNoTrace) (+ 0.24 (* t 0.76)) t))")
B(" (bind a1 %s)" % seg("t", 0.02, 0.30))
B(" (bind qa (- 2.0 (* 2.0 a1)))")
B(" (bind sweep (select (< a1 0.5) (* 4.0 (* a1 (* a1 a1))) (- 1.0 (* 0.5 (* qa (* qa qa))))))")
B(" (bind a2 %s)" % seg("t", 0, 0.05))
B(" (bind a3 %s)" % seg("t", 0.28, 0.38))
B(" (bind head (* 3.2 (* %s (- 1.0 %s))))" % (S("a2"), S("a3")))
B(" (bind a4 %s)" % seg("t", 0.26, 0.42))
B(" (bind a5 %s)" % seg("t", 0.46, 0.60))
B(" (bind tglow (* (+ 1.0 (* 0.5 (Math|Trig|Sin(Radians) (* 3.14159 a4)))) (- 1.0 %s)))" % S("a5"))
B(" (bind b1 %s)" % seg("tb", 0.24, 0.34))
B(" (bind q1 (- 1.0 b1))")
B(" (bind sx (Math|Float|Max(Float) (- 1.0 (* q1 (* q1 q1))) 0.001))")
B(" (bind b2 %s)" % seg("tb", 0.30, 0.54))
B(" (bind q2 (- 2.0 (* 2.0 b2)))")
B(" (bind o (select (< b2 0.5) (* 4.0 (* b2 (* b2 b2))) (- 1.0 (* 0.5 (* q2 (* q2 q2))))))")
B(" (bind b3 %s)" % seg("tb", 0.36, 0.56))
B(" (bind q3 (- 2.0 (* 2.0 b3)))")
B(" (bind sz (+ 0.05 (* 0.95 (select (< b3 0.5) (* 4.0 (* b3 (* b3 b3))) (- 1.0 (* 0.5 (* q3 (* q3 q3))))))))")
B(" (bind b4 %s)" % seg("tb", 0.30, 0.60))
B(" (bind flash (- 1.0 %s))" % S("b4"))
B(" (bind b5 %s)" % seg("tb", 0.42, 0.56))
B(" (bind b6 (Math|Trig|Sin(Radians) (* 3.14159 %s)))" % seg("tb", 0.86, 1.0))
B(" (bind lglow (* %s (+ 1.0 (* 0.25 (* b6 b6)))))" % S("b5"))
B(" (bind u %s)" % seg("tb", 0.52, 0.80))
B(" (bind um (- u 1.0))")
B(" (bind k (+ 1.0 (+ (* 2.2 (* um (* um um))) (* 1.2 (* um um)))))")
B(" (bind b7 %s)" % seg("tb", 0.60, 0.86))
B(" (bind mflash (* 0.35 (- 1.0 %s)))" % S("b7"))
B(" (bind b8 %s)" % seg("tb", 0.70, 0.86))
B(" (bind tipg (+ %s (* 1.6 (Math|Trig|Sin(Radians) (* 3.14159 b8)))))" % S("b8"))
B(" (bind b9 %s)" % seg("tb", 0.80, 1.0))
B(" (bind late %s)" % S("b9"))
B(" (bind n (Math|Vector|Normalize (Variables|Default|GetFaceAxis)))")
B(" (bind pv (Variables|Default|GetPv))")
B(" (bind scl (+ (* (Math|Vector|MakeVector 1.0 1.0 1.0) sx) (* (* n n) (- sz sx))))")
B(" (bind rot (Math|Vector|RotatorfromAxisandAngle (Variables|Default|GetAx) (* (Variables|Default|GetTh) (- 1.0 o))))")
B(" (bind op (Math|Transform|ComposeTransforms (Math|Transform|ComposeTransforms (Math|Transform|MakeTransform :Location (* pv -1.0)) (Math|Transform|MakeTransform :Rotation rot :Scale scl)) (Math|Transform|MakeTransform :Location pv)))")
B(" (bind bodies (Variables|Default|GetBodies))")
B(" (for c bodies")
B("  (bind i (Utilities|Array|FindItem bodies c))")
B("  (Transformation|SetRelativeTransform c (Math|Transform|ComposeTransforms (Utilities|Array|Get(acopy) (Variables|Default|GetBodyRest) i) op))")
B("  (Rendering|SetVisibility c (>= tb 0.24))")
B("  (Rendering|Material|SetScalarParameterValueonMaterials c \"Flash\" flash)")
B("  (Rendering|Material|SetScalarParameterValueonMaterials c \"AppearGlow\" lglow))")
B(" (bind movers (Variables|Default|GetMovers))")
B(" (for c movers")
B("  (bind i (Utilities|Array|FindItem movers c))")
B("  (Transformation|SetRelativeTransform c (Math|Transform|ComposeTransforms (Utilities|Array|Get(acopy) (Variables|Default|GetMoverRest) i) (Math|Transform|MakeTransform :Location (* (Variables|Default|GetMoverHide) (- 1.0 k)))))")
B("  (Rendering|SetVisibility c (> u 0.0))")
B("  (Rendering|Material|SetScalarParameterValueonMaterials c \"Flash\" mflash)")
B("  (Rendering|Material|SetScalarParameterValueonMaterials c \"AppearGlow\" tipg))")
B(" (for c (Variables|Default|GetTraces)")
B("  (Rendering|SetVisibility c (and (not (Variables|Default|GetNoTrace)) (or (> head 0.0001) (and (> sweep 0.0001) (> tglow 0.0001)))))")
B("  (Rendering|Material|SetScalarParameterValueonMaterials c \"Sweep\" sweep)")
B("  (Rendering|Material|SetScalarParameterValueonMaterials c \"Head\" head)")
B("  (Rendering|Material|SetScalarParameterValueonMaterials c \"Glow\" tglow))")
B(" (for c (Variables|Default|GetLates)")
B("  (Rendering|Material|SetScalarParameterValueonMaterials c \"AppearGlow\" late)))")
print("\n".join(L))
