;; ===== LifeWander (T P Seed) -> suma de 3 senos a razones 1 : raiz2 : raiz5 (nunca se realinean);
;; pesos 1 : 0,8 : 0,6 (critica: con 1 : 0,5 : 0,25 el 76 % de la varianza iba al fundamental = vaiven periodico)
(fn LifeWander (T P Seed)
  (bind _w (/ 6.2831853 (Math|Float|Max(Float) P 0.1)))
  (bind _a (* _w T))
  (return (/ (+ (+ (Math|Trig|Sin(Radians) (+ _a Seed))
                   (* 0.8 (Math|Trig|Sin(Radians) (+ (+ (* 1.41421 _a) (* 1.7 Seed)) 1.3))))
                (* 0.6 (Math|Trig|Sin(Radians) (+ (+ (* 2.23607 _a) (* 2.9 Seed)) 4.1))))
             2.4)))

;; ===== SortArm (Index Arm): orden de dibujo del brazo contra la membrana del nucleo, con histeresis.
;; Atras = prioridad 4 (la membrana del nucleo es 5; con 1+Index el brazo 4 empataba y el 5 quedaba delante).
(fn SortArm (Index Arm)
  (bind _d (Math|Vector|Normalize (- (Utilities|Array|Get(acopy) (Variables|Z-Interno|GetPos) Index) (Variables|Z-Interno|GetCoreC))))
  (bind _lean (.x _d))
  (bind _was (Utilities|Array|Get(acopy) (Variables|Z-Interno|GetArmBack) Index))
  (bind _now (select (> _was 0.5) (select (> _lean -0.05) 0.0 1.0) (select (< _lean -0.1) 1.0 0.0)))
  (if (!= _now _was)
    (Rendering|SetTranslucentSortPriority Arm (select (> _now 0.5) 4 (+ 10 Index)))
    (Utilities|Array|SetArrayElem (Variables|Z-Interno|GetArmBack) Index _now)))

(fn SortArms ()
  (CallFunction|SortArm :Index 0 :Arm (Variables|Default|GetArm0))
  (CallFunction|SortArm :Index 1 :Arm (Variables|Default|GetArm1))
  (CallFunction|SortArm :Index 2 :Arm (Variables|Default|GetArm2))
  (CallFunction|SortArm :Index 3 :Arm (Variables|Default|GetArm3))
  (CallFunction|SortArm :Index 4 :Arm (Variables|Default|GetArm4))
  (CallFunction|SortArm :Index 5 :Arm (Variables|Default|GetArm5)))

;; ===== LifeStep (DT Snap): relojes integrados, temperamento, nucleo flotante, actitud, pulso por grupo
(fn LifeStep (DT Snap)
  (Utilities|Array|Resize (Variables|Z-Interno|GetLifeP) 6)
  (Utilities|Array|Resize (Variables|Z-Interno|GetLifeGather) 6)
  (Utilities|Array|Resize (Variables|Z-Interno|GetLifeTurn) 6)
  (Utilities|Array|Resize (Variables|Z-Interno|GetArmBack) 6)
  (Variables|Z-Interno|SetAgS (select Snap (Variables|1-Estado|GetAgitation) (Math|Interpolation|FInterpTo (Variables|Z-Interno|GetAgS) (Variables|1-Estado|GetAgitation) DT (Variables|1-Estado|GetStateSmoothing))))
  (bind _ag (Math|Float|Clamp(Float) (Variables|Z-Interno|GetAgS) 0.0 1.0))
  (bind _s (Variables|Z-Interno|GetS))
  (bind _u (Math|Float|Clamp(Float) (/ (- _s 0.2) 0.7) 0.0 1.0))
  (bind _c (* (* _u _u) (- 3.0 (* 2.0 _u))))
  (Variables|Z-Interno|SetTempo (* (* (Variables|4-Vida|GetOrganicMotion) (Math|Float|Lerp 1.2 0.7 _c)) (+ 1.0 (* 0.4 _ag))))
  (Variables|Z-Interno|SetAmpS (* (* (Variables|4-Vida|GetFloatAmount) (Math|Float|Lerp 1.0 0.55 _c)) (+ 1.0 (* 0.35 _ag))))
  (bind _pre (and Snap (not (Variables|Z-Interno|GetLifeBooted))))
  (Variables|Z-Interno|SetTau (select _pre (* (Variables|4-Vida|GetPreviewTime) (Variables|Z-Interno|GetTempo)) (+ (Variables|Z-Interno|GetTau) (* DT (Variables|Z-Interno|GetTempo)))))
  (Variables|Z-Interno|SetPhase (select _pre (Math|Float|%(Float) (* (* (* 0.8975979 (Math|Float|Max(Float) (Variables|4-Vida|GetPulseSpeed) 0.05)) (+ 1.0 (* 0.4 (Variables|1-Estado|GetAgitation)))) (Variables|4-Vida|GetPreviewTime)) 6.2831853) (Variables|Z-Interno|GetPhase)))
  (Variables|Z-Interno|SetLifeBooted (or (Variables|Z-Interno|GetLifeBooted) (not Snap)))
  (bind _uk (Math|Float|Clamp(Float) (/ (- _s 0.7) 0.25) 0.0 1.0))
  (Variables|Z-Interno|SetKappa (* (* _uk _uk) (- 3.0 (* 2.0 _uk))))
  (bind _ca (Variables|2-Forma|GetCenterAttraction))
  (bind _v1 (Math|Float|Clamp(Float) (/ (- _s 0.6) 0.2) 0.0 1.0))
  (bind _v2 (Math|Float|Clamp(Float) (/ (- _s 0.8) 0.2) 0.0 1.0))
  (bind _v3 (Math|Float|Clamp(Float) (/ (- _s 0.3) 0.3) 0.0 1.0))
  (bind _rc (* (* (Variables|2-Forma|GetCentreRadius) (+ 1.0 (* (* 0.25 (+ (* 0.4 (* (* _v1 _v1) (- 3.0 (* 2.0 _v1)))) (* 0.6 (* (* _v2 _v2) (- 3.0 (* 2.0 _v2)))))) _ca))) 1.025))
  (bind _gc (* (* (* _rc (+ 0.12 (* 0.06 _s))) (Math|Float|Max(Float) (Variables|3-Membrana|GetMembraneThickness) 0.3)) 1.15))
  (Variables|Z-Interno|SetRMin (+ (+ (+ (* _rc (+ 1.0 (* (* (* 0.75 (Variables|4-Vida|GetNoiseAmount)) (+ 1.0 (* 0.4 _ag))) (- 1.0 (* 0.5 (Variables|Z-Interno|GetCoh)))))) _gc) (* (* (* _ca 0.22) _rc) (* (* _v3 _v3) (- 3.0 (* 2.0 _v3))))) (+ (* 7.2 (Math|Float|Max(Float) (Variables|2-Forma|GetGroupSize) 0.05)) 1.0)))
  (bind _t8 (Math|Float|Clamp(Float) (/ _s 0.8) 0.0 1.0))
  (Variables|Z-Interno|SetRShift (Math|Float|Max(Float) 0.0 (- (+ (Variables|Z-Interno|GetRMin) 1.0) (* (* (Math|Float|Lerp (Variables|2-Forma|GetDistSeparated) (* (Variables|2-Forma|GetDistConnected) (- 1.15 (* 0.15 _ca))) (* (* _t8 _t8) (- 3.0 (* 2.0 _t8)))) (Variables|2-Forma|GetGroupSpread)) 0.82))))
  (bind _t (Variables|Z-Interno|GetTau))
  (bind _wx (CallFunction|LifeWander :T _t :P 23.7 :Seed 0.0))
  (bind _wy (CallFunction|LifeWander :T _t :P 17.9 :Seed 1.9))
  (bind _wz (CallFunction|LifeWander :T _t :P 11.3 :Seed 3.7))
  (bind _coh (Variables|Z-Interno|GetCoh))
  (bind _fm (* (Variables|Z-Interno|GetAmpS) (- 1.0 (* 0.5 _coh))))
  (bind _cn (Math|Vector|MakeVector (* (* 2.0 _fm) _wx) (* (* 4.0 _fm) _wy) (+ (* (* 6.0 _fm) _wz) (* (* (Variables|4-Vida|GetFloatAmount) _coh) (Math|Trig|Sin(Radians) (Variables|Z-Interno|GetPhase))))))
  (Variables|Z-Interno|SetCoreD (select Snap (Math|Vector|VectorZero) (- _cn (Variables|Z-Interno|GetCoreC))))
  (Variables|Z-Interno|SetCoreC _cn)
  (bind _wyaw (CallFunction|LifeWander :T _t :P 53.0 :Seed 0.4))
  (bind _wpit (CallFunction|LifeWander :T _t :P 41.0 :Seed 2.2))
  (bind _wrol (CallFunction|LifeWander :T _t :P 67.0 :Seed 5.1))
  (bind _fa (* (Variables|4-Vida|GetFloatAmount) (Math|Float|Lerp 1.0 0.7 _c)))
  (Variables|Z-Interno|SetFigRot (Math|Rotator|MakeRotator :Roll (* (* 6.0 _fa) _wrol) :Pitch (* (* 2.5 _fa) _wpit) :Yaw (* (* 4.0 _fa) _wyaw)))
  (bind _tr (Math|Trig|DegreesToRadians (Variables|2-Forma|GetFigureTilt)))
  (Variables|Z-Interno|SetPlaneN (Math|Vector|RotateVector :A (Math|Vector|MakeVector (Math|Trig|Cos(Radians) _tr) 0.0 (Math|Trig|Sin(Radians) _tr)) :B (Variables|Z-Interno|GetFigRot)))
  (for _i (range 6)
    (bind _fi (Math|Conversions|ToFloat(Integer) _i))
    (bind _g (Math|Float|Fraction (+ (* 0.618034 _fi) 0.2)))
    (bind _wp (CallFunction|LifeWander :T _t :P (* 15.0 (+ 0.82 (* 0.36 _g))) :Seed (+ (* 2.39996 _fi) 0.9)))
    (Utilities|Array|SetArrayElem (Variables|Z-Interno|GetLifeP) _i _wp)
    (Utilities|Array|SetArrayElem (Variables|Z-Interno|GetLifeGather) _i 1.0)
    (Utilities|Array|SetArrayElem (Variables|Z-Interno|GetLifeTurn) _i 0.0)))

;; ===== LifeApply (Index): la vida propia de UN grupo, sobre el Tgt que dejo GroupTarget
(fn LifeApply (Index)
  (bind _fi (Math|Conversions|ToFloat(Integer) Index))
  (bind _g (Math|Float|Fraction (+ (* 0.618034 _fi) 0.2)))
  (bind _k (+ 0.82 (* 0.36 _g)))
  (bind _sd (* 2.39996 _fi))
  (bind _tr (Math|Trig|DegreesToRadians (Variables|2-Forma|GetFigureTilt)))
  (bind _n0 (Math|Vector|MakeVector (Math|Trig|Cos(Radians) _tr) 0.0 (Math|Trig|Sin(Radians) _tr)))
  (bind _tg (Variables|Default|GetTgt))
  (bind _h0 (Math|Vector|DotProduct _tg _n0))
  (bind _v (- _tg (* _n0 _h0)))
  (bind _r0 (Math|Float|Max(Float) (Math|Vector|VectorLength _v) 1.0))
  (bind _er (* _v (/ 1.0 _r0)))
  (bind _et (Math|Vector|Normalize (Math|Vector|CrossProduct _n0 _er)))
  (bind _R (+ (* _r0 (Utilities|Array|Get(acopy) (Variables|Z-Interno|GetLifeGather) Index)) (Variables|Z-Interno|GetRShift)))
  (bind _rm (Variables|Z-Interno|GetRMin))
  (bind _lf (Math|Float|Max(Float) (- _R _rm) 0.0))
  (bind _t (Variables|Z-Interno|GetTau))
  (bind _wr (CallFunction|LifeWander :T _t :P (* 29.0 _k) :Seed _sd))
  (bind _ws (CallFunction|LifeWander :T _t :P (* 21.0 _k) :Seed (+ _sd 2.1)))
  (bind _wd (CallFunction|LifeWander :T _t :P (* 17.0 _k) :Seed (+ _sd 4.2)))
  (bind _a (Variables|Z-Interno|GetAmpS))
  (bind _coh (Variables|Z-Interno|GetCoh))
  (bind _r1 (+ (+ _R (* (* (* 0.25 _lf) _a) (* (- 1.0 _coh) _wr))) (* (* _R (Math|Float|Lerp (* 0.045 _a) (* 0.05 (Variables|4-Vida|GetFloatAmount)) _coh)) (Utilities|Array|Get(acopy) (Variables|Z-Interno|GetLifeP) Index))))
  (bind _dr (- _r1 _rm))
  (bind _r1c (* 0.5 (+ (+ _r1 _rm) (Math|Float|Sqrt (+ (* _dr _dr) 4.0)))))
  (bind _nf (Math|Conversions|ToFloat(Integer) (Math|Integer|Clamp(Integer) (Variables|2-Forma|GetGroupCount) 1 6)))
  (bind _gap (/ 6.2831853 _nf))
  (bind _thc (* 2.0 (Math|Trig|Asin(Radians) (Math|Float|Min(Float) 1.0 (/ (+ (* 24.0 (Math|Float|Max(Float) (Variables|2-Forma|GetGroupSize) 0.05)) 2.0) (* 2.0 _r1c))))))
  (bind _thm (Math|Float|Max(Float) (* 0.5 (- _gap (+ (/ 2.2 _nf) _thc))) 0.001))
  (bind _x (+ (* (* (* 0.085 (Math|Float|Min(Float) _gap 2.094)) _a) (* (- 1.0 (* 0.7 _coh)) _ws)) (Utilities|Array|Get(acopy) (Variables|Z-Interno|GetLifeTurn) Index)))
  (bind _q (/ _x _thm))
  (bind _dth (/ _x (Math|Float|Sqrt (+ 1.0 (* _q _q)))))
  (bind _dh (* (* 5.0 _a) (* (- 1.0 (* 0.5 _coh)) _wd)))
  (bind _rel (+ (* (+ (* _er (Math|Trig|Cos(Radians) _dth)) (* _et (Math|Trig|Sin(Radians) _dth))) _r1c) (* _n0 (+ _h0 _dh))))
  (Variables|Default|SetTgt (+ (Variables|Z-Interno|GetCoreC) (Math|Vector|RotateVector :A _rel :B (Variables|Z-Interno|GetFigRot))))
  (Utilities|Array|SetArrayElem (Variables|Z-Interno|GetPos) Index (+ (Utilities|Array|Get(acopy) (Variables|Z-Interno|GetPos) Index) (* (Variables|Z-Interno|GetCoreD) (Variables|Z-Interno|GetKappa))))
  (bind _w (* (* 1.25 (+ 0.85 (* 0.3 _g))) (+ 1.0 (* 0.25 _coh))))
  (Variables|Z-Interno|SetSprW2 (* _w _w))
  (Variables|Z-Interno|SetSprD (* 1.44 _w)))

;; ===== LifeLV (): pisa LV0 (centro flotante), LV1.z (Agitation suavizada) y LV4 (plano rotado)
(fn LifeLV ()
  (bind _c (Variables|Z-Interno|GetCoreC))
  (bind _p (Variables|Z-Interno|GetPlaneN))
  (Variables|Default|SetLV0 (Math|Color|MakeColor (.x _c) (.y _c) (.z _c) (Variables|2-Forma|GetCentreRadius)))
  (Variables|Default|SetLV1 (Math|Color|MakeColor (Variables|Z-Interno|GetS) (Variables|Z-Interno|GetPhase) (Variables|Z-Interno|GetAgS) (Variables|1-Estado|GetColorTemp)))
  (Variables|Default|SetLV4 (Math|Color|MakeColor (.x _p) (.y _p) (.z _p) (Variables|3-Membrana|GetEnvelopeHug)))
  (CallFunction|SortArms))
