;; BP_LovingCell_SC — VIDA fase 2 (la calma reorganiza la entidad). Escrito 2026-09-27, con la critica aplicada.
;; Variables nuevas: 4-Vida: Reach (1, editable). Z-Interno: Psi PairA BridgeL BridgeTm BridgeV BridgeQ (float[]),
;;   ScrL ScrTm ScrV ScrP (float), NPrev (int).
;; Empalmes: Simulate: LifeStep -> CalmStep -> ForLoop(StepGroup) ; ForLoop(BridgeP rampa).Completed -> BridgeStep.
;; 🔴 bind NO es asignacion: todo lo que se lee DESPUES de mutar un arreglo se materializa en una variable Scr*.

;; ===== CalmStep (DT Snap): coherencia, pulsos enganchados a la respiracion (PLL), llegada escalonada,
;;       afinidad de parejas y su inclinacion (antes de comprometerse)
(fn CalmStep (DT Snap)
  (Utilities|Array|Resize (Variables|Z-Interno|GetPsi) 6)
  (Utilities|Array|Resize (Variables|Z-Interno|GetPairA) 6)
  (bind _s (Variables|Z-Interno|GetS))
  (bind _ag (Math|Float|Clamp(Float) (Variables|Z-Interno|GetAgS) 0.0 1.0))
  (bind _uc (Math|Float|Clamp(Float) (/ (- _s 0.5) 0.4) 0.0 1.0))
  (Variables|Z-Interno|SetCoh (* (* (* _uc _uc) (- 3.0 (* 2.0 _uc))) (- 1.0 (* 0.7 _ag))))
  (bind _coh (Variables|Z-Interno|GetCoh))
  (bind _wb (* (* 0.8975979 (Math|Float|Max(Float) (Variables|4-Vida|GetPulseSpeed) 0.05)) (+ 1.0 (* 0.4 (Variables|1-Estado|GetAgitation)))))
  (bind _ph (Variables|Z-Interno|GetPhase))
  (bind _dcon (* (Variables|2-Forma|GetDistConnected) (- 1.15 (* 0.15 (Variables|2-Forma|GetCenterAttraction)))))
  (bind _dsep (Variables|2-Forma|GetDistSeparated))
  (bind _uw (Math|Float|Clamp(Float) (/ _s 0.8) 0.0 1.0))
  (bind _dnom (Math|Float|Max(Float) (Math|Float|Lerp _dsep _dcon (* (* _uw _uw) (- 3.0 (* 2.0 _uw)))) 1.0))
  (bind _t (Variables|Z-Interno|GetTau))
  (bind _pre (Variables|4-Vida|GetPreviewTime))
  (for _i (range 6)
    (bind _fi (Math|Conversions|ToFloat(Integer) _i))
    (bind _g (Math|Float|Fraction (+ (* 0.618034 _fi) 0.2)))
    (bind _wf (* (/ 6.2831853 (* 15.0 (+ 0.82 (* 0.36 _g)))) (Variables|Z-Interno|GetTempo)))
    (bind _tgt (- _ph (+ 1.0 (* 0.3 (- _g 0.5)))))
    (bind _ps0 (Utilities|Array|Get(acopy) (Variables|Z-Interno|GetPsi) _i))
    (bind _d0 (- (+ (* 2.39996 _fi) (* _wf _pre)) _tgt))
    (bind _wr0 (- _d0 (* 6.2831853 (Math|Float|Round (/ _d0 6.2831853)))))
    (bind _psN (select Snap (+ _tgt (* (- 1.0 _coh) _wr0)) (+ _ps0 (* DT (+ (Math|Float|Lerp _wf _wb _coh) (* (* 0.9 _coh) (Math|Trig|Sin(Radians) (- _tgt _ps0))))))))
    (Utilities|Array|SetArrayElem (Variables|Z-Interno|GetLifeP) _i (Math|Float|Lerp (Utilities|Array|Get(acopy) (Variables|Z-Interno|GetLifeP) _i) (* 0.5 (+ (Math|Trig|Sin(Radians) _psN) 1.0)) _coh))
    (bind _ug (Math|Float|Clamp(Float) (/ (- _s (* 0.18 (Math|Float|Fraction (+ (* 0.618034 _fi) 0.5)))) 0.8) 0.0 1.0))
    (Utilities|Array|SetArrayElem (Variables|Z-Interno|GetLifeGather) _i (/ (Math|Float|Lerp _dsep _dcon (* (* _ug _ug) (- 3.0 (* 2.0 _ug)))) _dnom))
    (bind _wa (CallFunction|LifeWander :T _t :P (* 47.0 (+ 0.8 (* 0.4 (Math|Float|Fraction (+ (* 0.618034 _fi) 0.77))))) :Seed (+ 0.9 (* 2.39996 _fi))))
    (bind _ua (Math|Float|Clamp(Float) (/ (- _wa 0.3) 0.55) 0.0 1.0))
    (Utilities|Array|SetArrayElem (Variables|Z-Interno|GetPairA) _i (* (* _ua _ua) (- 3.0 (* 2.0 _ua))))
    (Utilities|Array|SetArrayElem (Variables|Z-Interno|GetPsi) _i (- _psN (* 6.2831853 (Math|Float|Floor (/ _psN 6.2831853))))))
  (bind _n (Math|Integer|Clamp(Integer) (Variables|2-Forma|GetGroupCount) 1 6))
  (bind _gap (/ 6.2831853 (Math|Conversions|ToFloat(Integer) _n)))
  (bind _us (Math|Float|Clamp(Float) (/ (- _s 0.15) 0.25) 0.0 1.0))
  (bind _lean0 (* (* (* (* (* 0.14 _gap) (Variables|4-Vida|GetReach)) (Variables|Z-Interno|GetAmpS)) (* (* _us _us) (- 3.0 (* 2.0 _us)))) (- 1.0 (* 0.6 _coh))))
  (for _j (range 6)
    (bind _pj (Math|Integer|%(Integer) (+ (- _j 1) _n) _n))
    (bind _dj (select (and (>= _n 3) (< _j _n)) (* (* _lean0 (Utilities|Array|Get(acopy) (Variables|Z-Interno|GetPairA) _j)) (- 1.0 (Math|Float|Clamp(Float) (* 2.0 (- (Utilities|Array|Get(acopy) (Variables|Z-Interno|GetBridgeP) _j) 0.5)) 0.0 1.0))) 0.0))
    (bind _dp (select (>= _n 3) (* (* _lean0 (Utilities|Array|Get(acopy) (Variables|Z-Interno|GetPairA) _pj)) (- 1.0 (Math|Float|Clamp(Float) (* 2.0 (- (Utilities|Array|Get(acopy) (Variables|Z-Interno|GetBridgeP) _pj) 0.5)) 0.0 1.0))) 0.0))
    (Utilities|Array|SetArrayElem (Variables|Z-Interno|GetLifeTurn) _j (select (< _j _n) (- _dj _dp) 0.0))))

;; ===== BridgeStep (DT Snap): puentes con MEMORIA (histeresis 0,12 + 2,5 s), primero ALCANZAN (dedos), despues cierran.
;;       Estado propio BridgeQ (la rampa vieja pisa BridgeP cada cuadro). Umbral por pareja desde su cercania
;;       NOMINAL (hash del angulo, sin vaiven ni inclinacion: sin realimentacion). Reset al cambiar GroupCount.
(fn BridgeStep (DT Snap)
  (Utilities|Array|Resize (Variables|Z-Interno|GetBridgeL) 6)
  (Utilities|Array|Resize (Variables|Z-Interno|GetBridgeTm) 6)
  (Utilities|Array|Resize (Variables|Z-Interno|GetBridgeV) 6)
  (Utilities|Array|Resize (Variables|Z-Interno|GetBridgeQ) 6)
  (bind _n (Math|Integer|Clamp(Integer) (Variables|2-Forma|GetGroupCount) 1 6))
  (bind _chg (!= _n (Variables|Z-Interno|GetNPrev)))
  (bind _s (Variables|Z-Interno|GetS))
  (bind _ag (Math|Float|Clamp(Float) (Variables|Z-Interno|GetAgS) 0.0 1.0))
  (for _b (range 6)
    (bind _bf (Math|Conversions|ToFloat(Integer) _b))
    (bind _jf (Math|Conversions|ToFloat(Integer) (Math|Integer|%(Integer) (+ _b 1) _n)))
    (bind _hb (Math|Float|Fraction (* (Math|Trig|Sin(Radians) (+ (* _bf 12.9898) 4.1414)) 43758.5453)))
    (bind _hj (Math|Float|Fraction (* (Math|Trig|Sin(Radians) (+ (* _jf 12.9898) 4.1414)) 43758.5453)))
    (bind _prox (Math|Float|Clamp(Float) (* -0.35 (- _hj _hb)) -0.5 0.5))
    (bind _on (Math|Float|Clamp(Float) (+ (- (+ 0.62 (* 0.1 (- (Math|Float|Fraction (+ (* 0.618034 _bf) 0.35)) 0.5))) (* 0.4 _prox)) (* 0.05 _ag)) 0.45 0.8))
    (bind _L (select _chg 0.0 (Utilities|Array|Get(acopy) (Variables|Z-Interno|GetBridgeL) _b)))
    (bind _tm0 (select _chg 0.0 (Utilities|Array|Get(acopy) (Variables|Z-Interno|GetBridgeTm) _b)))
    (bind _exc (select (> _L 0.5) (- (- _on 0.12) _s) (- _s _on)))
    (bind _tm (select (select (> _L 0.5) (< _s (- _on 0.12)) (> _s _on)) (+ _tm0 (* DT (+ 1.0 (* 6.0 (Math|Float|Clamp(Float) (/ (- _exc 0.06) 0.1) 0.0 1.0))))) 0.0))
    (Variables|Z-Interno|SetScrL (select Snap (select (> _s (- _on 0.06)) 1.0 0.0) (select (> _tm 2.5) (- 1.0 _L) _L)))
    (Variables|Z-Interno|SetScrTm (select (or (> _tm 2.5) Snap) 0.0 _tm))
    (bind _ue (Math|Float|Clamp(Float) (/ (- _s (- _on 0.35)) 0.32) 0.0 1.0))
    (bind _bw (* (* (* _ue _ue) (- 3.0 (* 2.0 _ue))) (+ 0.3 (* 0.7 (Utilities|Array|Get(acopy) (Variables|Z-Interno|GetPairA) _b)))))
    (bind _bud (select (< _bw 0.05) 0.0 (Math|Float|Min(Float) 0.49 (* (* 0.5 (Variables|4-Vida|GetReach)) _bw))))
    (bind _uf (Math|Float|Clamp(Float) (/ (- _s _on) (Math|Float|Max(Float) (- (Math|Float|Min(Float) (+ _on 0.22) 0.92) _on) 0.01)) 0.0 1.0))
    (bind _q0 (Utilities|Array|Get(acopy) (Variables|Z-Interno|GetBridgeQ) _b))
    (bind _v0 (Utilities|Array|Get(acopy) (Variables|Z-Interno|GetBridgeV) _b))
    (bind _pT (select (and (>= _n 3) (< _b _n)) (select (> (Variables|Z-Interno|GetScrL) 0.5) (Math|Float|Max(Float) (+ 0.5 (* 0.5 (Math|Float|Max(Float) 0.12 (* (* _uf _uf) (- 3.0 (* 2.0 _uf)))))) (select (and (> _q0 0.79) (> _s (+ _on 0.06))) 0.81 0.0)) _bud) 0.0))
    (Variables|Z-Interno|SetScrV (select Snap 0.0 (Math|Float|Clamp(Float) (+ _v0 (* DT (- (* 1.69 (- _pT _q0)) (* 2.6 _v0)))) -0.35 0.35)))
    (Variables|Z-Interno|SetScrP (select Snap _pT (Math|Float|Clamp(Float) (+ _q0 (* DT (Variables|Z-Interno|GetScrV))) 0.0 1.0)))
    (Utilities|Array|SetArrayElem (Variables|Z-Interno|GetBridgeQ) _b (Variables|Z-Interno|GetScrP))
    (Utilities|Array|SetArrayElem (Variables|Z-Interno|GetBridgeV) _b (Variables|Z-Interno|GetScrV))
    (Utilities|Array|SetArrayElem (Variables|Z-Interno|GetBridgeTm) _b (Variables|Z-Interno|GetScrTm))
    (Utilities|Array|SetArrayElem (Variables|Z-Interno|GetBridgeL) _b (Variables|Z-Interno|GetScrL))
    (Utilities|Array|SetArrayElem (Variables|Z-Interno|GetBridgeP) _b (Variables|Z-Interno|GetScrP)))
  (Variables|Z-Interno|SetNPrev _n))
